### ISSUE TITLE
Cannot PASTE into "Destination Address" field when sending. 

### ISSUE THREAD

**Issue by cube60** [stratisproject/Breeze#135]
I'm using a a MacBook Pro Running SIerra 10.12.5, pasting in the send address field isn't working.

**Comment by Yzord** [comment]
This needs to be done for it

https://pracucci.com/atom-electron-enable-copy-and-paste.html

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] OS X copy/paste](https://trello.com/c/nE7QKJc7/84-wallet-gui-os-x-copy-paste)

**Comment by dev0tion** [comment]
Fixed in #151
