### ISSUE TITLE
blank popup and small suggestions

### ISSUE THREAD

**Issue by spectator-on-slack** [stratisproject/Breeze#139]
1. Have the wallet address we sent coins to/received coins from listed in the details instead of just the transaction id. Make it show up on History tab without having to click on details (its own column).

2. When you enter the wrong password when sending and click Send nothing happens. Add a popup error message like "Please input the correct password to send BTC".

3. **BUG:** I get this random popup. I think its triggered after sending coins to someone. It just randomly popups after a few minutes from sending the coins. After clicking OK, it shows my balance again and transaction history.

![randompopup](https://user-images.githubusercontent.com/29806775/27757412-fdaa3602-5db5-11e7-990e-78b9d2905cc3.jpg)

![afterclickok](https://user-images.githubusercontent.com/29806775/27757414-0464126a-5db6-11e7-89ef-fe373d9af544.jpg)

**Comment by spectator-on-slack** [comment]
I think the blank popup is the popup others are getting about connecting to the API.

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Blank pop-up](https://trello.com/c/rHyT3AsS/94-wallet-gui-blank-pop-up)

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Check password when sending](https://trello.com/c/nmq5aWKs/95-wallet-gui-check-password-when-sending)

**Comment by Abalalojik** [comment]
Hello, I also have this problem, but it happened after I've used a faucet to receive coins.

**Comment by dev0tion** [comment]
Resolved
