### ISSUE TITLE
Some issues on Mac Sierra

### ISSUE THREAD

**Issue by Yzord** [stratisproject/Breeze#140]
Some on them are already known in Slack, but not here as an issue

1. Closing the wallet with the red button on the left isn't working flawlessly. Wallet keeps coming back. Right click Quit in dock is working as of Quit Breeze-ui in the toolbar.

2. No copy paste inside the wallet. When try to send the BTC address cannot be pasted. Also copying isn't allowed.  

3. When i keep the sending window too long open it shuts down the connection with the API. Wallet needs to be restarted then (which is annoying) https://s16.postimg.org/e9m1lfuj9/Screen_Shot_2017-07-01_at_11.44.48.png

**Comment by Yzord** [comment]
Send is not working. When i fill in (by hand) address, amount and pass i can push Send what i want...it isn't sending.

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] General stability OS X](https://trello.com/c/gX9dEiDR/96-wallet-gui-general-stability-os-x)

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] OS X copy/paste](https://trello.com/c/nE7QKJc7/84-wallet-gui-os-x-copy-paste)

**Comment by dev0tion** [comment]
1) This is probably an Electron bug and should be fixed in an upcoming version
2) Fixed
3) Fixed
