### ISSUE TITLE
Khilone (Mac)

### ISSUE THREAD

**Issue by Khilone** [stratisproject/Breeze#141]
Some outgoing transactions aren't showing in latest transactions and history.

Sometimes a window pops open out of nothing, and it contains no information besides the logo.

**Comment by prc454** [comment]
same issue here. First 3 transactions were fine, then the tbtc sent to Khilone were not recorded in history or displayed on the dashboard.  The balance was adjusted.
Windows10

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Blank pop-up](https://trello.com/c/rHyT3AsS/94-wallet-gui-blank-pop-up)

**Comment by dev0tion** [comment]
Resolved
