### ISSUE TITLE
Right click menu doesn't work on form inputs (like password)

### ISSUE THREAD

**Issue by mikedennis** [stratisproject/Breeze#142]
Used often for cut/paste.

Something seems to flash quickly when you try to right click into the form inputs (like password). I have a simple angular/bootstrap app with form and I can paste into the input so suspect it might be the css template.

Might also be bootstrap, my test app is running an older bootstrap "bootstrap": "3.3.7" 

I'm running Win7

**Comment by bokobza** [comment]
Thanks for the feedback @mikedennis  :ok_hand:

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Right click to copy/paste](https://trello.com/c/rdDyVnfs/93-wallet-gui-right-click-to-copy-paste)

**Comment by dev0tion** [comment]
Fixed in #156
