### ISSUE TITLE
Feedback from @evju (Win10)

### ISSUE THREAD

**Issue by evju** [stratisproject/Breeze#143]
**When restoring wallet:**
No right click paste option. (User friendliness)
Name box should be above password (for a more logical structure)

**History:**
Send text should be in past tense; sent (grammar)

**Logout:**
Logout needs confirmation check box

**Other Suggestions:**
Make it possible to open transaction details by clicking on the box, instead of going to the allocated "details" link (Personal preference)
Add a "minimize to tray" option
Add a "close to tray" option

**Comment by bokobza** [comment]
Thanks for the feedback @evju :ok_hand:

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Name box above password box](https://trello.com/c/8iXvXCLO/97-wallet-gui-name-box-above-password-box)

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Right click to copy/paste](https://trello.com/c/rdDyVnfs/93-wallet-gui-right-click-to-copy-paste)

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Logout confirmation](https://trello.com/c/Cl2UrYUV/85-wallet-gui-logout-confirmation)

**Comment by dev0tion** [comment]
Thanks a lot for the feedback mate!

1) Fixed in #156 
2) Done in #150 
3) Send/Receive is the transaction "type", so it is correct.
4) Done in #156 
5) We have considered this, but it will be popping up a modal every time a user accidentally clicks a transaction. To be continued.
6+7) This will get added in the future.

**Comment by evju** [comment]
Nice work! Happy to help! 👍 

About issue 3.

My thinking was that when looking at **Recent Transactions** and in **History**, the "Receive" type is renamed "Received", but the "Send" type is still "Send", which is a very minor grammatical error. (Assuming we are thinking about these transactions as something that happened in the past) 

You could even rename "Received" to "Receive" (For consistency)

It's not a very important change, just some minor polish. 😄
