### ISSUE TITLE
Restrict Input of 'Field'

### ISSUE THREAD

**Issue by tjandy98** [stratisproject/Breeze#148]
As I suggested on the slack channel (https://stratisplatform.slack.com/archives/C5F5GGLC8/p1499129535356492)

Allow only numerical input in the 'amount' field when sending coins. As of now, any input can be entered,

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] 1 - Only allow numerical entries in send amount](https://trello.com/c/ksXUCpMC/112-wallet-gui-1-only-allow-numerical-entries-in-send-amount)

**Comment by dev0tion** [comment]
Done in #161, thank you for your feedback!
