### ISSUE TITLE
No User Feedback When Attempting to Send Unconfirmed Balances

### ISSUE THREAD

**Issue by XCBatman** [stratisproject/Breeze#149]
1. When attempting to send any amount before any transaction has been confirmed, and thus using a balance where 100% is allocated to "Unconfirmed Balance", no popup is received when clicking send. Would expect some kind of user notification explaining why the transaction cannot complete.
2. [Minor] Under the details of a transaction, for the "TYPE" field the 'R' in "Received" is not capitalized. 
3. When selecting the fee, having a field to input a value (which would then correspondingly move the slider bar) may also be useful, rather than using the slider only. 
4. No error/notification provided to the user when using a non-complex password (i.e "123"). Maybe a warning, or restricting passwords to something might be necessary.

And as others have stated, I've received the blank popup, and it would be nice when clicking on a transaction that the details page would open without having to click the 'details' button.

**Comment by XCBatman** [comment]
5. No ability to set a default wallet. If I create two wallets, it appears that the wallets are always listed in alphabetical order.

**Comment by XCBatman** [comment]
6. Sent transactions are duplicated in the history tab and under the Dashboard. Received transactions appear only once, as expected. 
7. Attempting to send negative amounts doesn't result in an error. Would expect only positive amounts are allowed. Additionally, in the amount field, any character can be entered. Should only be numeric input.

**Comment by dev0tion** [comment]
1) Done in #161 
2) Will be added in this sprint
3) We will be having 3 fee types that are selectable by the fee slider: fast, average and slow. But it's a good idea to at least show the fee amount.
4) Good idea, added to backlog
5) They will probably remain alphabetic for a while. Maybe when we need a config file we can add a default wallet parameter
7) Fixed in #161
