### ISSUE TITLE
Decrypt wallet - switch to a btn-link class

### ISSUE THREAD

**Issue by bep42** [stratisproject/Breeze#157]
We have to switch the button below into a `btn-link` class contrary to `btn-darkgray`

<img width="1185" alt="capture d ecran 2017-07-07 a 14 36 18" src="https://user-images.githubusercontent.com/6614362/27958161-0cb8e7bc-6322-11e7-8e9c-96fd0b40e06b.png">

**Comment by dev0tion** [comment]
Done in #161
