### ISSUE TITLE
Modal block details - remove the class

### ISSUE THREAD

**Issue by bep42** [stratisproject/Breeze#158]
We should remove the class `blockLabel ` into the `<span>` to use the whole and good CSS style.

![screen shot 2017-07-10 at 16 02 01](https://user-images.githubusercontent.com/6614362/28021737-39d88964-6589-11e7-9f2f-b9a2f0feabd5.png)

See below when the `blocklabel` class is removed : 

<img width="480" alt="screen shot 2017-07-10 at 16 04 14" src="https://user-images.githubusercontent.com/6614362/28021834-8128d990-6589-11e7-9abe-bd41f8796c36.png">

**Comment by dev0tion** [comment]
Done in #161
