### ISSUE TITLE
WalletWrapper Load todo comment

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#18]
File: https://github.com/stratisproject/Breeze/blob/master/Breeze/src/Breeze.Wallet/Wrappers/WalletWrapper.cs  
  
Code:  
```
/// <summary>
/// Loads a wallet from the local device.
/// </summary>
/// <param name="password">The user's password.</param>
/// <param name="folderPath">The folder where the wallet will be loaded.</param>
/// <param name="name">The name of the wallet.</param>
/// <returns>The wallet loaded from the local device</returns>
public WalletModel Load(string password, string folderPath, string name)
{
	Safe wallet = Safe.Load(password, Path.Combine(folderPath, $"{name}.json"));

	//TODO review here which data should be returned
	return new WalletModel
	{
		Network = wallet.Network.Name,
		Addresses = wallet.GetFirstNAddresses(10).Select(a => a.ToWif()),
		FileName = wallet.WalletFilePath
	};
}
```
As I described in the [ApiSpecification](https://github.com/stratisproject/Breeze/blob/master/Breeze.Documentation/ApiSpecification.md), I think no data should be returned, except success or fail.  
  
If you really want to return something then it should be the same as either `GET /wallet/general` or `GET /wallet/status`. But as I said, I don't think it makes sense to return stuff for simplicity, since they could just call those two functions.  
  
Same applies to the `Recover`. (Same ToDo comment there.)  
  
Thoughts?

**Comment by bokobza** [comment]
Usually in Web APIs, when you access or create a resource of some sort, it is returned in the response.
We might want to add to the wallet model object later (maybe "last received block" or whatever).
Also, if we can do something in a single call, it's better than to do it in multiple. 
Here the response doesn't tell us anything new but I don't see the point of changing it.
I'm happy for it to stay as it is.

**Comment by nopara73** [comment]
It only has to tell if the loading was success or not.  
  
If you insist in a response then we should give back a `wallet/general` response then.  
  
```
{
  "success": "true",
  "walletFilePath": "path to the wallet file",
  "encryptedSeed": "6PYKWP34en1wELfcJDgXaFRPugjgkDdEk2p2Pzytm1158dxgNyLAUXwpKL",
  "chainCode": "q/Fn7+RSIVM0p0Nj6rIuNkybF+0WKeSZPMQS2QCbDzY=",
  "network": "main", // main/testnet
  "creationTime": "2017-03-21",
  "decrypted": "true",
  "uniqueId": "sadwpiqjdpijwqdpijwqidjoi" // can only get if decrypted, if not it's empty string
}
```

**Comment by bokobza** [comment]
no data is returned at the moment.
Closing this.
