### ISSUE TITLE
Console takeover by the main process

### ISSUE THREAD

**Issue by Aprogiena** [stratisproject/Breeze#181]
I'm running breeze-ui.exe (v0.1.0 alpha) and if I run it from say Windows Explorer, all is fine. However, if I run it from console (most notably FAR Manager, but cmd.exe has the same problem), the wallet process takes over the console, which is not what you expect as a user - suddenly you can work in the console (in cmd.exe try "dir" + ENTER) and at the same time you get output from the wallet process to this very same console. This is very inconvenient (esp. for FAR Manager users, because what you use FAR for is basically running all the stuff in your system, so you don't expect anyone to break your console like this).

**Comment by nopara73** [comment]
@Aprogiena I canno reproduce it. Can you confirm I'm doing it right?

1. I use Windows 7, x64, I downloaded from https://github.com/stratisproject/Breeze#ci-build  
2. Then I fire up cmd in the unzipped folder and write `breeze-ui` (I login, click on a couple of things)   
  
From here I can work in the same console and no output from Breeze is being forwarded there.

**Comment by Aprogiena** [comment]
Just tried it with the latest build from the link you provided (somehow it is also v0.1.0 alpha) and it behaves differently, but the problem is still there. Somehow more silent now.

Easiest way to reproduce it now is:
- delete appdata folder
- spawn a new cmd.exe and type breeze-ui
- wait 10 sec
- then you close the cmd.exe's window (this should kill your breeze which is a related bug) 
- then spawn a new shell and run breeze-ui again (this should kill your daemon, another bug)
- click close in the crash dialog -> your new console should be owned

**Comment by bokobza** [comment]
Here is the exception thrown in the console:
![image](https://user-images.githubusercontent.com/1867877/30636180-ab650a9e-9dec-11e7-8da9-44aeababf16b.png)

**Comment by bokobza** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Breeze-UI] Console takeover by the main process](https://trello.com/c/jPt4iWB1/238-breeze-ui-console-takeover-by-the-main-process)

**Comment by bokobza** [comment]
We'll fix this with a keepalive API call.
Closing. Will fix in https://github.com/stratisproject/Breeze/issues/314.
