### ISSUE TITLE
WalletController Recover cannot check password

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#19]
File: `https://github.com/stratisproject/Breeze/blob/master/Breeze/src/Breeze.Wallet/Controllers/WalletController.cs`  
  
Code:  
```
[Route("recover")]
[HttpPost]
public IActionResult Recover([FromBody]WalletRecoveryRequest walletRecovery)
{
    // checks the request is valid
    if (!this.ModelState.IsValid)
    {
        var errors = this.ModelState.Values.SelectMany(e => e.Errors.Select(m => m.ErrorMessage));
		return ErrorHelpers.BuildErrorResponse(HttpStatusCode.BadRequest, "Formatting error", string.Join(Environment.NewLine, errors));
	}

    try
    {
        var wallet = this.walletWrapper.Recover(walletRecovery.Password, walletRecovery.FolderPath, walletRecovery.Name, walletRecovery.Network, walletRecovery.Mnemonic);
        return this.Json(wallet);

    }
    catch (FileNotFoundException e)
    {
		// indicates that this wallet does not exist
		return ErrorHelpers.BuildErrorResponse(HttpStatusCode.NotFound, "Wallet not found.", e.ToString());				
    }
    catch (SecurityException e)
    {
		// indicates that the password is wrong
		return ErrorHelpers.BuildErrorResponse(HttpStatusCode.Forbidden, "Wrong password, please try again.", e.ToString());
	}
    catch (Exception e)
    {
		return ErrorHelpers.BuildErrorResponse(HttpStatusCode.BadRequest, e.Message, e.ToString());
	}
}
```
The password will never be wrong. It'll recover a wallet with the wrong password neverthless, it cannot check if the right password is added or not.  
  
Details:  
*Load*: walletfile + password = extkey  
*Recover* mnemonic + password = extkey   
   
The thing is while at load the walletfile contains the encrypted extkey therefore it only decrypts it with the right password, it knows if the password is wrong, else it cannot decrypt it, while at recover the mnemonic and the password generates a whole new extkey. If you add password: "foo", but in reality it was "bar", then it won't know if the generated one was the same or not.

**Comment by bokobza** [comment]
I see, thanks for pointing that out.
I guess we need to change the word 'password' in Recover to 'passphrase' to be more exact, am I correct?

**Comment by nopara73** [comment]
According to google the differences between the word 'password' and 'passphrase' are minor, so I there is no need for renaming.
  
> The main difference of the two is that passwords do not have spaces while passphrases have spaces and are longer than any random string of letters.

**Comment by bokobza** [comment]
took care of this in commit https://github.com/stratisproject/Breeze/pull/31/commits/5eb5a26ba91a8853ddeaaf914ee916bee0ae31b6
