### ISSUE TITLE
[Priority: Medium] Wallet Recovery: Optional Creation Date

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#192]
Why is the creation date optional? What happens if it's not provided?
![](http://i.imgur.com/HGSZxAG.png)

**Comment by dev0tion** [comment]
It used to have a default value, but it seems something has changed.
I've added a bug on trello, a user was getting the offset error after not entering a date.

**Comment by nopara73** [comment]
Then it's a UI job. Please make it mandatory. Maybe you can change the label to: "Earliest Possible Creation Date" or "Syncronize From". That would be more descriptive for the user, it would not worry about if "Do I remember the date correctly? What country was I when I created? How does the wallet even handle that?" Etc...

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Make recovery date mandatory](https://trello.com/c/rt62CuHT/265-wallet-gui-make-recovery-date-mandatory)

**Comment by dev0tion** [comment]
Done in #248
