### ISSUE TITLE
[Priority: High] Too strong password requirement

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#193]
![](http://i.imgur.com/5D47fw1.png)  
  
Is it possible to loosen the password requirements? 99% of people will forget it (including me), because they are not used to such passwords.  
  
In fact I'd advocate not holding the hands of the users and go with zero restrictions, even enable empty string for password.

**Comment by dev0tion** [comment]
Discussed with @bokobza yesterday. 
We will leave as is for now, we can always implement less strict password requirements later.
Going from easy to more strict is more difficult (as a lot of user passwords wont be allowed anymore).

**Comment by nopara73** [comment]
Discussed with @dangershony. We should not leave it like this.

**Comment by dangershony** [comment]
I would say to allow zero password (no restriction) on the wallet. the BIP specifies that so we should confirm to the BIP.

**Comment by bokobza** [comment]
The BIP specifies that that passphrase is optional, but don't we want the user to protect their wallet?
At the moment the password is assigned as the passphrase so we always have the passphrase. If we want to make the passphrase optional (like the BIP said), we'll lose the password. 
We can decouple them and have password + passphrase but that's confusing to the user.

**Comment by nopara73** [comment]
Against for decoupling. Then the user would end up writing down the passphrase next to the mnemonics, which defeats the purpose of passphrase.  
I'd prefer zero restrictions on password/passphrase, but I'm also ok with simply weakening the current nightmare requirements.

**Comment by nopara73** [comment]
I investigated and tested the API. The UI is the only one that makes the password hard.  The API only fails if it the password is empty.   
@dev0tion Please lower it to min 6 character and don't require capital letters and digits.

**Comment by bokobza** [comment]
We can probably remove the requirements so that the only requirement is to have a password.
@dev0tion what do you think?

**Comment by dev0tion** [comment]
Yeah sure, I'm ok with it.
If we remove restrictions I'd suggest even setting no password should be possible, to be compliant with BIP as Dan suggested.

**Comment by dev0tion** [comment]
Done in #250 
For now the only requirement is that a user fills in a password. No rules on the pattern of it.
