### ISSUE TITLE
[Priority: High] Wallet creation explanation

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#194]
![](http://i.imgur.com/O0Rib3w.png)  

It should have a more detailed explanation, like (or exactly) this:  

![](http://i.imgur.com/767ldM2.png)

**Comment by bep42** [comment]
I agree. I've suggested this and it's also bootstrapped : 

<img width="583" alt="capture d ecran 2017-08-29 a 13 22 24" src="https://user-images.githubusercontent.com/6614362/29818602-56a6a9ee-8cbd-11e7-8cc5-c623cef6aeec.png">

**Comment by nopara73** [comment]
Resolved.
