### ISSUE TITLE
[Priority: Medium] Copypasteable popups

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#195]
As the title says, it would be good if we would not throw up native windows (like ever). Or at the very least mnemonic words should be copypasteable.  
  
Copypasting such in Windows with "ctrl+c" is possible, but not intuitive. 

![](http://i.imgur.com/sLtjZZ7.png)

**Comment by nopara73** [comment]
![](http://i.imgur.com/U05XBRi.png)  

This popup for example is nice and consistent with the theme for the wallet.

**Comment by nopara73** [comment]
@bep42 's suggestion is also beautiful: https://github.com/stratisproject/Breeze/issues/194#issuecomment-325634449

<img width="583" alt="capture d ecran 2017-08-29 a 13 22 24" src="https://user-images.githubusercontent.com/6614362/29818602-56a6a9ee-8cbd-11e7-8cc5-c623cef6aeec.png">

**Comment by dev0tion** [comment]
Yes, that has been planned for quite some time now.

**Comment by dev0tion** [comment]
Popups copy pastable since #279
