### ISSUE TITLE
[Priority: Low] Build for production error (on Windows)

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#198]
As described in the [UI build readme](https://github.com/stratisproject/Breeze/blob/master/Breeze.UI/README.md) one must build for production with `npm run electron:dev`. However the daemon does not get copied into the `\assets` folder and the building process complains about it.

**Comment by nopara73** [comment]
I tagged it with low priority, because it is likely a problem of the documentation or it's only present on my system.

**Comment by dev0tion** [comment]
electron:dev requires the user to be running the daemon himself, this starts electron in development mode (with the chrome developer tools enabled).
It's not meant for production.

**Comment by nopara73** [comment]
Please either fix in the documentation or take it out of it.
