### ISSUE TITLE
Add graceful shutdown

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#20]
When the apllication is closing it should take a few seconds to persist the unsaved things to the disk, dispose connections, etc...   
  
A simple code like this shuld happen there:  
```
cts.Cancel();
walletJobTask.Wait()
```

**Comment by bokobza** [comment]
Good idea.
I'll keep this open for now as I need to see how this can be done properly when taking into consideration the graceful shutdown of the underlying full node components.

**Comment by bokobza** [comment]
done
