### ISSUE TITLE
[Priority: Medium] Incorrect Send Amount

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#204]
![](http://i.imgur.com/xkJvwdL.png)  

The above send and receive transactions are actually one transaction, where I sent 0.1btc to myself. In this case the fee is not deducted from the receive. While in this case it's not a big problem, but such bug might cause other inconsistencies and issues.

**Comment by nopara73** [comment]
@bokobza I tested it, the problem is still present. It's possible the submodule had not been updated yet and that's why the problem is still present.  

### Correction
It's actually not the receive amount what's incorrect, but the send amount.  
So if the user wants to send 0.1btc, it'll send 0.1btc plus fees, but receive 0.1btc. So the send amount is the incorrect one, not the receive.

**Comment by nopara73** [comment]
I moved this under UI label, because as @dev0tion you talked with @bokobza it is likely, because the fee is not added to the sending amount, but discarded by the UI.

**Comment by dev0tion** [comment]
Done in #271

**Comment by nopara73** [comment]
@dev0tion Are you sure about it? It turned out to be an API bug, not an UI bug, I just forgot to update this issue. If so feel free to close the issue.

**Comment by dev0tion** [comment]
Yes mate, Jeremy fixed the API bug and I display it correctly in the UI.
