### ISSUE TITLE
[Priority: Medium] Paid fee should be shown before sending

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#206]
![](http://i.imgur.com/GA3auvi.png)

Right now the user chooses the fee priority, but it doesn't know in advance what fee it will pay. There should be an estimation shown before sending.

**Comment by nopara73** [comment]
It's a UI challenge only. `build-transaction` returns the fee.

**Comment by nopara73** [comment]
I propose having a "Calculate Fee" button, next to the "Send" button, which will call build-transaction. Then shows the fee for the user.

**Comment by dev0tion** [comment]
I should probably calculate the fee  automatically when
a) the form is valid (all fields are ok)
b) something changes

No need for an extra button then.

**Comment by nopara73** [comment]
It's possible you could do some rough estimates, however fee estimation is not an easy job.  
The main problem with fee estimation is that it's non-deterministic, in order to calculate the fee you need to be aware of the number of inputs, but in order to be aware of the number of inputs you need to know the fee.  

Maybe you want to call build-transaction every time the user changes something in the UI. I suspect that's fast enough.

**Comment by dev0tion** [comment]
Yeah, that's what I was saying. Call build-transaction on each change of the form.

**Comment by nopara73** [comment]
Closing, estimatefee has been added.
