### ISSUE TITLE
Daemon doesn't run when I start Breeze-ui.exe

### ISSUE THREAD

**Issue by RobertMCarr** [stratisproject/Breeze#219]
Downloaded a fresh copy to the 64bit windows 10 wallet onto a computer that hasn't had the wallet running before.  Breeze loads and sits on the initialising screen.  Fiddler showed that it was failing to connect to the /api/wallet/files endpoint.  Turned out the Breeze.Daemon.exe isn't automatically being run by the wallet.

**Comment by Aprogiena** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[POS] Implement checkpointing similarly to StratisX](https://trello.com/c/4JPKjiDt/231-pos-implement-checkpointing-similarly-to-stratisx)

**Comment by dev0tion** [comment]
@RobertMCarr have you tried running the daemon.exe in command line?
What error do you get?

Make sure to add: light -testnet to the start.

**Comment by RobertMCarr** [comment]
Hi @dev0tion I didn't get any errors.  The UI just never got past the "loading the future" screen.  However since the last release, I don't have this problem but I have seen those that do in the slack.

To confirm, running it in the command line with "light -testnet" worked but i had to do it before running the UI.
