### ISSUE TITLE
[Priority: Medium] Bring Breeze under StratisBitcoinFullNode repository

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#227]
It'd dramatically improve development time. Is there any reason why not do this?
@dangershony @bokobza @dev0tion

**Comment by bokobza** [comment]
yes it's in the plan.
We need to make sure we import the commits history and that the builds are still working so that only the Breeze.Daemon exe is used with the UI.
Not difficult by any means, we'll do it soon.

**Comment by nopara73** [comment]
https://github.com/stratisproject/Breeze/pull/241
