### ISSUE TITLE
[Priority: Medium] Change ports in a conscious way

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#240]
Replaces: https://github.com/stratisproject/Breeze/issues/79  

I propose Breeze's ports to be chosen within a long range of unassigned IANA ports, based on [this](https://stackoverflow.com/a/28369841/2061103) statistics, but also checked against [Service Name and Transport Protocol Port Number Registry](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml) to avoid port collision.  
  
A reference of common local ports currently used by Breeze and related softwares:  

|Port  | Application |
|----  | ---- |
|37120 | HiddenWallet API |
|37121 | Tor socks port used by HiddenWallet |
|37122 | Tor control port used by HiddenWallet |
|37123 | NTumbleBit server |
|37124 | Tor socks port used by NTumbleBit |
|37125 | Tor control port used by NTumbleBit |
|9050  | Default Tor socks port |
|9051  | Default Tor control port |
|9150  | Tor socks port used by Tor Browser |
|9151  | Tor control port used by Tor Browser |
|8333  | Bitcoin Core Mainnet RPC |
|18333  | Bitcoin Core Testnet RPC |
|18444  | Bitcoin Core Regtest RPC |
|5000  | Stratis: Bitcoin node and Breeze Wallet API |
|5105  | Stratis: Stratis node and Stratis Wallet API |

**Comment by bokobza** [comment]
Yeah every ASP.NEt Core app is using port 5000 so having the Bitcoin node on this port is prob not the best idea.
I don't think it's a high priority at the moment though.
I guess we'll can at some point just replace all instances of 5000 and 5105 in our code by new values.
