### ISSUE TITLE
[Priority: High] How to display unconfirmed change amount

### ISSUE THREAD

**Issue by dev0tion** [stratisproject/Breeze#246]
Currently when sending funds the change balance is viewed as unconfirmed, e.g.:
- I have 1 BTC in one UTXO.
- I send 0.2 BTC to X.
- 0.8 BTC went to a change address and shows as unconfirmed.

Which is normal behavior, but people aren't used to seeing this. 
Other wallets just show this as confirmed (while it's actually unconfirmed) in the UI.

Should I just display one balance, being unconfirmed + confirmed, since we allow unconfirmed UTXO's to be spend anyway or what shall we do? Fight!

**Comment by bokobza** [comment]
@dangershony @nopara73 What do you guys think?
I'm happy to leave it as it is for now, as it's factually correct. Although I appreciate it can be a bit unsettling.

**Comment by nopara73** [comment]
That's a very tricky question. I took days to figure out how I should show it, and still not sure what is the best.  
I'd vote for leave as is. Knowing ourselves we'd just end up in endless procrastination :)

**Comment by nopara73** [comment]
2 votes for leave it as is. @dev0tion, please reopen this issue if you don't agree.
