### ISSUE TITLE
[Priority: Low] Beautify ugly dropdown boxes

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#254]
![](https://i.imgur.com/bzi7nrR.png)

**Comment by bokobza** [comment]
I think this is on Windows only.
@dev0tion and @bep42 can confirm.

**Comment by bokobza** [comment]
ah it's actually the same on Linux.

**Comment by dev0tion** [comment]
This is one for @bep42

**Comment by dev0tion** [comment]
Done in #285
