### ISSUE TITLE
[Priority: Medium] Wallet Restore Bug

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#257]
When we try to restore the wallet that we already have the following message appears:  
![](https://i.imgur.com/ikNMB6x.png)  

However now we have 2 wallets with the same name: the stratis one and the bitcoin one. So the instruction should be removing both. It's a little tricky for reasons I don't go into it, instead I ask the question: why don't we delete the old and actually restore the user's wallet as it wishes it?

**Comment by bokobza** [comment]
it's true that this could be automated, but I want to prevent the user from doing it by mistake and him have to resync his whole wallet.
This is like us saying "Are you sure you want to do this?"

**Comment by nopara73** [comment]
I'd vote for resyncing, it's unlikely the user would want to recover a wallet that he's already using, unless it messed up creation time. But don't insist.  
So how would you tell the user to delete both wallet file? We have a stratis and a bitcoin process. One process knows about only one wallet file. You cannot throw an exception that knows about both.

**Comment by bokobza** [comment]
Hmm that's true, although at this point I don't want to introduce new things that are not absolutely necessary to the code. We may want to add this as an improvement to the next version, though.
For the error, you're right. We can probably think of a way to say it so that user knows what to do.

**Comment by nopara73** [comment]
Fixed: https://github.com/stratisproject/Breeze/pull/260
