### ISSUE TITLE
[Priority: High] From and To does not make sense

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#258]
When you click on transaction details of sent or received transactions "From" address and "To" address does not make sense.  

How Bitcoin works: When a wallet does not have enough transaction on one unspent transaction output, it'll add another one to add up the inputs. In this case you'd have two input addresses (From).  
In fact when a wallet sends a transaction it'll usually send it to 2 bitcoin addresses, one is the change.  
With this in mind a solution could be to add multiple "from" and "to" addresses, but it's not that simple:  

In fact the Bitcoin network does not know Bitcoin addresses, it only knows transaction outputs, which consists of a value and a scriptpubkey. Often scriptpubkeys cannot be translated to Bitcoin addresses.  
So when the wallet receives a transaction where one of its input cannot be translated to a traditional Bitcoin address it'll not know how to work.  
In fact if Breeze in the future want to do anything a little advanced (TumbleBit, Lightning Network, CoinJoin, OP_RETURN) the From and To will also not work properly.  

![](https://i.imgur.com/p7KDkEp.png)  
![](https://i.imgur.com/edleumd.png)

**Comment by dev0tion** [comment]
I can remove that line

**Comment by bokobza** [comment]
please do @dev0tion. If you remember back when Benoit was doing the design we decided not to include from/to because you can never know whether it's gonna be 1 person or many.
And since we don't have access to the trx we can't show much.
We did talk about including a link to the trx on a block explorer, though.
Maybe something for vNext.

**Comment by dev0tion** [comment]
Sounds guuuud. Removing.

**Comment by nopara73** [comment]
The very notion you were able to extract such data from the API is worrisome. I believe this has something to do with the TransactionData concept, which should be refactored in the future. However that's a deep layer of the wallet so it requires some careful refactoring which would probably take weeks.

**Comment by dev0tion** [comment]
Done in #259
