### ISSUE TITLE
[Priority: Medium] Don't allow to delete a wallet file when node is running

### ISSUE THREAD

**Issue by dangershony** [stratisproject/Breeze#268]

**Comment by nopara73** [comment]
(1) Is it possible? (2) Does it even matter?  

**(2) Does it even matter?**  
The wallet file is stored in memory, it will be serialized eventually, so even if the wallet file is deleted, it'll reappear properly.  

**(1) Is it possible?**  
It may not be possible on every OS, but even if it is, I'd stay far away from OS permission management magic. You'll just end up building more bug into.

**Comment by dangershony** [comment]
I guess we could keep a lock on the file.
But point 2 makes sense so closing this.
