### ISSUE TITLE
[Priority: Low] Displaying fee on sent transaction details?

### ISSUE THREAD

**Issue by dev0tion** [stratisproject/Breeze#270]
Should we display the fee separately in the transaction details?

Like this maybe:
![image](https://user-images.githubusercontent.com/10409230/31229513-3ab24ce8-a9e1-11e7-9725-dc9dfea97a44.png)

@dangershony @nopara73 @bokobza

**Comment by nopara73** [comment]
Yes.

**Comment by bokobza** [comment]
yeah I think it's useful.

**Comment by dev0tion** [comment]
Ok. Adding it. Now just a matter of how:
- Like above
- Should I add a net total (total amount - fee)? Then it would be three lines: Total, net, fee

**Comment by nopara73** [comment]
Link above.

**Comment by bokobza** [comment]
agree with @nopara73

**Comment by dev0tion** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Wallet-GUI] Display fee on transaction details](https://trello.com/c/luZA7S1o/297-wallet-gui-display-fee-on-transaction-details)

**Comment by dev0tion** [comment]
Done in #282
