### ISSUE TITLE
Add extern alias for NStratis in Breeze projects

### ISSUE THREAD

**Issue by bokobza** [stratisproject/Breeze#29]
There is a problem upgrading the Stratis.Bitcoin nuget package where NStratis is used instead of NBitcoin because HBitcoin uses NBitcoin.
The namespaces in the 2 libraries are the same so we need to add NStratis as an external alias.
Tried to make it work, to no avail.

https://msdn.microsoft.com/en-us/library/yabyz3h4.aspx
https://stackoverflow.com/questions/35899657/how-to-extern-alias-an-assembly-with-net-core

 #https://github.com/dotnet/cli/issues/564

**Comment by dangershony** [comment]
NStratis is just an exact fork of NBitcoin with some additional POS code so perhaps HBitcoin should consider using NStratis for now.

It literally the exact same copy

**Comment by dev0tion** [comment]
If you say no NBitcoin code is changed, only POS added, I don't see why not. Up to @nopara73 I guess.
Eventually we will have to change it anyway, as we will be adding a Stratis wallet to Breeze as well.

**Comment by bokobza** [comment]
not using Hbitcoin anymore, so I'm closing this.
