### ISSUE TITLE
Sending small amounts without a leading zero should be allowed

### ISSUE THREAD

**Issue by mikeolteanu** [stratisproject/Breeze#296]
When sending small amounts like .01, you should be able to just put in .01 instead of having to put in 0.01

"Enter a valid amount. Only positive numbers are allowed." is the message that shows when there is no leading zero.

**Comment by dev0tion** [comment]
@bokobza I've prepared this for the UI.
Is the API capable of handling this?

**Comment by bokobza** [comment]
of course mate ;-)

**Comment by dev0tion** [comment]
Added
