### ISSUE TITLE
"Estimate Fee" button requires wallet password, but probably shouldn't

### ISSUE THREAD

**Issue by mikeolteanu** [stratisproject/Breeze#298]

**Comment by dangershony** [comment]
Yes correct we should be able to estimate fee without password.

**Comment by dev0tion** [comment]
Yes, once we have an estimate-fee endpoint we probably wont need a fee button anymore.

**Comment by mikedennis** [comment]
Should be an endpoint there now https://github.com/stratisproject/StratisBitcoinFullNode/commit/3d0cc86d3b0eccd549ac7263b221c1bb20555ddd

**Comment by dev0tion** [comment]
Done in #351
