### ISSUE TITLE
Failing to send coins due to node issues does not provide an error message

### ISSUE THREAD

**Issue by mikeolteanu** [stratisproject/Breeze#299]
When attempting to send funds on a overloaded node, the Send button goes gray after being clicked (assumably trying to send the funds), and then after about 10 seconds goes back to being clickable. 

There is no error message to inform the user about what happened. Were funds sent? Did funds fail to send? Will funds send sometime in the future after the transaction is resolved?

As well, during the attempted send, there should be a message like "Trying to send the funds" which is later cleared upon success/failure of the transaction.

**Comment by mikedennis** [comment]
I look into this and see what I can do to make this better.

**Comment by mikedennis** [comment]
Improved the error handling from the send-transaction api. Should be fixed by this PR https://github.com/stratisproject/StratisBitcoinFullNode/pull/673

**Comment by bokobza** [comment]
fixed
