### ISSUE TITLE
sharper icon on MacOS

### ISSUE THREAD

**Issue by mtaipe** [stratisproject/Breeze#302]
The user faraga suggest to have a sharp icon. The result on the picture comes form a macOS Sierra 10.12.6

![Screenshot](https://user-images.githubusercontent.com/31449449/31896198-bd5ec104-b845-11e7-9405-c25dd00e80fc.png)

**Comment by bep42** [comment]
It's in progress. `Dlow` is already aware of it. Thanks 👍

**Comment by Yzord** [comment]
Yeah, I also complained about it...looks too much win95

Fix it! :-P

**Comment by dev0tion** [comment]
I need to change code for this as well @bep42, I don't think the problem is the actual icns file.
I will fix it, as @Yzord said 😄

**Comment by dev0tion** [comment]
Done in #328
