### ISSUE TITLE
Change location of the Stratis Breeze Wallet Files

### ISSUE THREAD

**Issue by Daandamhuis** [stratisproject/Breeze#303]
Hi, 

On the C:\ of my server i have a shortage of storage (only 60GB). Is it possible to give the user the option to select an other drive, so I won't risk flooding the drive? 

I'm using Windows 10 x64 - Creaters Update Fall. 

With kind regards,
Daan Damhuis

**Comment by nlmaca** [comment]
What do you mean by this? I downloaded the win64bit zip file. I didn't have to install the wallet. Just move the files to your other drive and start the breeze-ui.exe again solved that part for me. Switched to 3 drives after that without any problems.

**Comment by dangershony** [comment]
I think you mean storage of the node data.
It's possible but not so easy, you need to go to the execution file and add a data location.

**Comment by Daandamhuis** [comment]
@dangershony Yes, that is correct. It's not something that is important for me now, but when it hits the mainnet, I would be a nice option to have.

**Comment by dev0tion** [comment]
@Daandamhuis yeah I agree, this should be possible in the future and was already on our future feature list.
