### ISSUE TITLE
Formatting of error when importing the same wallet twice could be better

### ISSUE THREAD

**Issue by bokobza** [stratisproject/Breeze#304]
> It's one long sentence, one for the btc wallet and one for the strat wallet. I'd like to see that in two alineas

**Comment by bokobza** [comment]
![image](https://user-images.githubusercontent.com/1867877/31953144-56e065fa-b8da-11e7-829e-d5d3e0aa09aa.png)

**Comment by bokobza** [comment]
@dev0tion is there any way for the UI to just show 1 message here?
I guess we'd have to create error message numbers or something similar.

**Comment by dev0tion** [comment]
Yeah it's possible, @nopara73 added this functionality, otherwise either the Stratis or the Bitcoin error messages don't get displayed.

**Comment by nopara73** [comment]
I only see a line feed problem with this message, nothing else.

@bokobza In this instance both the Stratis and the Bitcoin node throw you an error. You must tell the user to remove both files otherwise it won't get fixed.

**Comment by bokobza** [comment]
yes indeed @nopara73 . I wanted to find a way for @dev0tion to know what this error is about and show only one error for both coins. Something a bit better formatted.
I guess this can be made much better just with a bit of UI formatting magic.
