### ISSUE TITLE
Trim white spaces around address in send form

### ISSUE THREAD

**Issue by bokobza** [stratisproject/Breeze#305]

**Comment by dev0tion** [comment]
You mean the whitespaces before and after the inputs @bokobza?
![image](https://user-images.githubusercontent.com/10409230/32016565-91196254-b9c4-11e7-9431-ee5ae7c4bf62.png)

**Comment by bep42** [comment]
Inside the inputs ? At the first time we designed it, this place was reserved to an icon for displaying success / errors, like this below : 

<img width="344" alt="capture d ecran 2017-10-26 a 13 53 01" src="https://user-images.githubusercontent.com/6614362/32051468-03ad6b9a-ba55-11e7-9e21-909c45f76a30.png">

**Comment by dev0tion** [comment]
I want to add that, but I don't have seperate validators for each entry :(

**Comment by bokobza** [comment]
what I meant was for @dev0tion to trim the whitespaces before he makes the api call :-)

**Comment by dev0tion** [comment]
Ah right, I wasn't clear on that either. 
Doing that.

**Comment by bep42** [comment]
and btw, i've fixed the space inside the inputs ;)

**Comment by dev0tion** [comment]
Done in #351
