### ISSUE TITLE
Fix the success modal

### ISSUE THREAD

**Issue by bep42** [stratisproject/Breeze#306]
We should : 

- Remove the `Show details` link and displayed the whole informations directly
- Add the Tax ID to the listing 

![capture d ecran 2017-10-23 a 18 12 16](https://user-images.githubusercontent.com/6614362/31900152-d85d6cf8-b81d-11e7-82dc-19d584e02299.png)

**Comment by dev0tion** [comment]
Ok. I will do this.

**Comment by dev0tion** [comment]
Done in #327
