### ISSUE TITLE
Modal send - Error displaying

### ISSUE THREAD

**Issue by bep42** [stratisproject/Breeze#307]
The error for the `Destination address` is displaying wrong. There's 2 modals one over the other one. Look at the pic' below : 

![capture d ecran 2017-10-23 a 18 00 12](https://user-images.githubusercontent.com/6614362/31900592-4100f2ce-b81f-11e7-918c-798ac8b6f259.png)

We should only display it as the error for the `Amount` 👍

**Comment by dev0tion** [comment]
I don't see how we can change this @bep42?

**Comment by bep42** [comment]
Like the error is displaying for the amount

**Comment by dev0tion** [comment]
Aah ok. Doable!

**Comment by dev0tion** [comment]
Done in #351 
@bep42 you might want to style the feedback a little bit.
