### ISSUE TITLE
Mac OSX 10.12.6 error when clicking twice on tray icon

### ISSUE THREAD

**Issue by zomertje** [stratisproject/Breeze#308]
![screen shot 2017-10-23 at 18 53 05](https://user-images.githubusercontent.com/33035293/31902145-1a4b8dba-b824-11e7-9bc7-6775acec44e0.png)

when clicking twice on the tray icon, when it looks like it does not start. Maybe a nicer error :)

**Comment by dev0tion** [comment]
Thanks, I had this error before, but I wasn't able to reproduce this. Now I know how.
Will get fixed.

**Comment by dev0tion** [comment]
Fixed in #327
