### ISSUE TITLE
Send TSTRAT - payment fee is not updating when switching between available options

### ISSUE THREAD

**Issue by eQza** [stratisproject/Breeze#309]
**System:**
Windows 10, x64

**Actual Behaviour:**
When selecting between Transaction fees (low, medium,high) the estimate fee stayed at 0.00013800 TSTRAT.

**Expect Behaviour**
I am guessing that the fees should update when selecting the different options available

![image](https://user-images.githubusercontent.com/21050380/31902249-1ad9c18c-b81c-11e7-9290-81d0ff59c20d.png)

![image](https://user-images.githubusercontent.com/21050380/31902266-271b8ce6-b81c-11e7-844f-65a0db4361e6.png)

![image](https://user-images.githubusercontent.com/21050380/31902273-309d8256-b81c-11e7-8061-af38e3f3e598.png)

**Comment by bep42** [comment]
Yep for instance the workflow is : 

1. Select your `transaction fee`
2. Then, estimate it.

It will be improved and automatically generated when you switch between the fee options. No worries.

**Comment by nopara73** [comment]
In Stratis it's hardcoded. I think there are no different fees, everything is the same.

**Comment by dev0tion** [comment]
Yes, because our network is not busy yet, it is currently a set value.
