### ISSUE TITLE
Stratis side does not want to connect

### ISSUE THREAD

**Issue by Neurosploit** [stratisproject/Breeze#316]
I'm unable to get the stratis part started. Stratis does not connect..btc does. on my end port in use by the breeze strat process as expected. I'll keep messing with it to see what it is. Fresh wallet and appdata folder. Win10x64

> 
> ======Connection======
> 
> [2017-10-24 06:09:29.9758 40] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Node [::ffff:51.141.28.47]:26178 offline
> [2017-10-24 06:09:29.9820 40] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Reason: Unexpected exception while connecting to socket
> [2017-10-24 06:09:30.4060 43] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Node [::ffff:51.141.28.47]:26178 offline
> [2017-10-24 06:09:30.4060 43] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Reason: Unexpected exception while connecting to socket
> [2017-10-24 06:09:32.4747 43] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Node [::ffff:51.141.28.47]:26178 offline
> [2017-10-24 06:09:32.4747 43] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Reason: Unexpected exception while connecting to socket
> [2017-10-24 06:09:33.1264 40] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Node [::ffff:51.141.28.47]:26178 offline
> [2017-10-24 06:09:33.1264 40] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Reason: Unexpected exception while connecting to socket
> [2017-10-24 06:09:34.1540 37] INFO: Stratis.Bitcoin.FullNode.<StartPeriodicLog>b__70_0 ======Node stats====== 10/24/2017 06:09:34 agent StratisBitcoin:1.0.2
> Headers.Height:        0        Headers.Hash:         00000e246d7b73b88c9ab55f2e5e94d9e22d471def3df5ea448f5576b1d156b9
> LightWallet.Height:    0        LightWallet.Hash:     00000e246d7b73b88c9ab55f2e5e94d9e22d471def3df5ea448f5576b1d156b9
> 
> ======Wallets======
> Wallet: wallet1,             Confirmed balance: 0.00000000
> 
> ======Connection======
> 
> 
> [2017-10-24 06:09:34.2789 56] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Node [::ffff:51.141.28.47]:26178 offline
> [2017-10-24 06:09:34.2789 56] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Reason: Unexpected exception while connecting to socket
> [2017-10-24 06:09:35.8887 46] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Node [::ffff:51.141.28.47]:26178 offline
> [2017-10-24 06:09:35.8887 46] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Reason: Unexpected exception while connecting to socket
> [2017-10-24 06:09:36.8675 39] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Node [::ffff:51.141.28.47]:26178 offline
> [2017-10-24 06:09:36.8738 39] INFO: Stratis.Bitcoin.Connection.ConnectionManagerBehavior.AttachedNode_StateChanged Reason: Unexpected exception while connecting to socket

**Comment by Neurosploit** [comment]
Jeremy rebooted his node. That solved it. Closing the issue.

**Comment by mtaipe** [comment]
Cause is that there is only one seed server and this issue arise only the first time the wallet wants to discover the stratis network. There should be more seed server or a better way to broadcast the IP of those valid stratis nodes where BreezeD can connect the first time.
