### ISSUE TITLE
On Windows, the app window is showing a scroll bar 

### ISSUE THREAD

**Issue by bokobza** [stratisproject/Breeze#318]
![image](https://user-images.githubusercontent.com/1867877/31953673-7b44e3f2-b8db-11e7-8771-d6e64d812f1e.png)

This also happens when we send a transaction. When the fees are estimated, the window suddenly extends a bit, scroll bar is shown and then retracts.

**Comment by bep42** [comment]
I think we'll redesign the page to display it in a 2 columns template.
For the `send modal` the fee estimation button will be removed and normally we'll have no more problems with scrollbar.

**Comment by dev0tion** [comment]
@bep42 are you on this?

**Comment by bokobza** [comment]
no more scrollbar :-)
