### ISSUE TITLE
non-standard windows tray icon behavior 

### ISSUE THREAD

**Issue by noescape00** [stratisproject/Breeze#319]
1) LMB click on tray icon is expected to show\hide main windows, it does nothing at the moment. 
2) Closing main window is expected to reduce it to tray with an option to exit the application through RBM click on tray icon => exit.

**Comment by dev0tion** [comment]
1. I'll check, thanks
2. Not true, closing main window closes applications on everything but OS X.
In the future we will add an option to choose to minimize to tray on clicking X, but closing the app will be the default behavior.

**Comment by dev0tion** [comment]
1. Fixed in #327 
Thanks for reporting!
