### ISSUE TITLE
Failing scenario while sending funds to own address results a couple of minor issues

### ISSUE THREAD

**Issue by viilveer** [stratisproject/Breeze#320]
Problem: 
* Popup inside popup, is this legit?
* I think the account row is invalid
* Scrollbar appears

Steps to repro:
* Make new account
* Have 0 balance (STRAT or BTC)
* Send funds to your own account

Screen:
![image](https://user-images.githubusercontent.com/1699307/31967931-1f3698a2-b918-11e7-98ef-4f38154cce3b.png)

I'm using Win10 x64.

**Comment by dev0tion** [comment]
Fixed in #351 
The account entry is actually correct, the default account is called "account 0", that's why it says account account 0, if that makes sense 😄
