### ISSUE TITLE
Place the Stratis tab above Bitcoin tab

### ISSUE THREAD

**Issue by spectator-on-slack** [stratisproject/Breeze#321]
1. When we log into Breeze wallet, it should be set to Stratis as default instead of Bitcoin. The Stratis logo tab on the left should be above Bitcoin's. It would make sense to leave it how it is if your company is planning to market the Breeze wallet as a Bitcoin wallet though.

**Comment by ymseo** [comment]
it is right

**Comment by dev0tion** [comment]
We're re-discussing this internally.
I'm in favor of keeping Bitcoin on top.

**Comment by spectator-on-slack** [comment]
How about when a user creates their account on the Breeze wallet, it should ask which coin they would like to set as default (Stratis or Bitcoin). Later on there can be a settings tab to change these settings.

**Comment by dev0tion** [comment]
That's a good idea!

**Comment by bokobza** [comment]
In the end we're keeping bitcoin at the top.
Having a settings is a bit overkill, we only have 2 currencies.
Closing.
