### ISSUE TITLE
Crash if BrezeWallet started twice

### ISSUE THREAD

**Issue by AgXCz** [stratisproject/Breeze#322]
App stopped working if second instance was tried to open. Regular, tested on Win7-64.

![image](https://user-images.githubusercontent.com/33097510/32008468-8ffa9f2c-b9ac-11e7-978c-a7cd19d431d9.png)

**Comment by nhan8g** [comment]
Error message and close on Windows 10 64bits

![image](https://user-images.githubusercontent.com/33117455/32046083-2fb03846-ba6c-11e7-9ed1-96184e4c90f6.png)

**Comment by bokobza** [comment]
Fixed in https://github.com/stratisproject/StratisBitcoinFullNode/pull/1071
