### ISSUE TITLE
Sending - Estimate fee doesn't react to setting Low/Medium/Fast

### ISSUE THREAD

**Issue by AgXCz** [stratisproject/Breeze#323]
Estimate fee doesn't react to setting Low/Medium/Fast
Imho it should be possible also to change it additionaly and see amount.
![image](https://user-images.githubusercontent.com/33097510/32008939-e5443b4a-b9ad-11e7-989f-ec8edd081c14.png)

**Comment by dev0tion** [comment]
It does change, but because the Stratis testnet is not busy it will remain the same value.
If you have a look at Bitcoin you will notice it will change.
