### ISSUE TITLE
Sending - no option for MAX amount

### ISSUE THREAD

**Issue by AgXCz** [stratisproject/Breeze#325]
There is no option to send **max** amount - which is quite necessary if user wants to send all to another wallet.
Issue is that it is not possible to send all as there is that fee.

![image](https://user-images.githubusercontent.com/33097510/32009364-29d34714-b9af-11e7-92fa-0edb572d5ff1.png)

**Comment by dev0tion** [comment]
Thanks, closing because double: 
https://github.com/stratisproject/Breeze/issues/205
