### ISSUE TITLE
Active balance is incorrect during pending sending

### ISSUE THREAD

**Issue by AgXCz** [stratisproject/Breeze#332]
I tried to send some amount of TBTC to another wallet and suddenly also Active balance is incorrect. I sent 0,1 + 0,2 TBTC, but unconfirmed balance shows 0,798
See picture: 
![image](https://user-images.githubusercontent.com/33097510/32038451-467371de-ba2a-11e7-86e5-bde99e916ee4.png)

**Comment by dev0tion** [comment]
This is not incorrect, that's the way blockchain works. 
People get confused by this, we're discussing if we should show it like people expect or how it actually is...
