### ISSUE TITLE
Request: Total balance in History

### ISSUE THREAD

**Issue by AgXCz** [stratisproject/Breeze#333]
There is no total balance in History. 
User should have an overview of account during the time. In History there is just history of payments, not history of total (Active) balance.
I consider it quite important feature.

**Comment by dev0tion** [comment]
You can find your active balance in the dashboard.
History will do exactly as its name describes: show a history of your transactions, we wont be showing your balance there.

**Comment by AgXCz** [comment]
Imho it is standard feature.  To knwo, what was the balance when (in history).
For example Electrum:
![image](https://user-images.githubusercontent.com/33097510/32049545-b6a5c0ba-ba4d-11e7-94ec-dda1a13535b1.png)

**Comment by dev0tion** [comment]
Qt 😄 

![image](https://user-images.githubusercontent.com/10409230/32062909-29c84aae-ba76-11e7-98e3-2c2b53fac35f.png)
