### ISSUE TITLE
TSTRAT Syncing issue

### ISSUE THREAD

**Issue by AgXCz** [stratisproject/Breeze#334]
I have sent some amount to another wallet. Sent is already confirmed:
![image](https://user-images.githubusercontent.com/33097510/32038799-edeca682-ba2b-11e7-806a-24977bf76ab0.png)
But in the same time receive is not confirmed:
![image](https://user-images.githubusercontent.com/33097510/32038842-15b33596-ba2c-11e7-8012-8c4052fb4b42.png)
There is some Syncing issue:
![image](https://user-images.githubusercontent.com/33097510/32038964-8d7c1138-ba2c-11e7-8aa3-ed18c4c2717f.png)
Even both wallets have the same 4 connections.

**Comment by nhan8g** [comment]
My Strat Breeze alway Sync on status
![image](https://user-images.githubusercontent.com/33117455/32042935-78db39f2-ba63-11e7-9c34-f9385d4e7a36.png)

**Comment by dev0tion** [comment]
Yes thanks, we are resolving the syncing issues.
An updated binary will be provided once the fix is deployed.

**Comment by AgXCz** [comment]
In my case (at one machine) it was still syncing (got stacked, payments still pending), but when I closed that app and re-started, then it was immediately ok, Synced 100% and payment Confirmed.

**Comment by dev0tion** [comment]
Hey @AgXCz 
First of all thank you so much for the extensive testing.
Though resolved in your case, I'm just going to leave this issue open untill we have deployed a general fix.

**Comment by AgXCz** [comment]
(Sorry, it was closed by mistake, I am not experienced in Git and didn't know meaning of [Close and comment])

**Comment by dev0tion** [comment]
No problem!

**Comment by joaquinbasci** [comment]
I have the same problem as nhan8g, it's stuck at syncing.

![captura de pantalla 2017-10-27 a la s 21 04 16](https://user-images.githubusercontent.com/20111400/32129187-c9acae36-bb5a-11e7-9252-e4d7ebc8fecc.png)

I restarted it a few times but nothing happens. Also, one time appeared a problem that said that it was unable to connect with the api or something like that.

**Comment by dev0tion** [comment]
Fixed in v0.2.1 of the beta.
