### ISSUE TITLE
Could you design a button to enhance UI for this screen

### ISSUE THREAD

**Issue by nhan8g** [stratisproject/Breeze#335]
![image](https://user-images.githubusercontent.com/33117455/32043116-08240af8-ba64-11e7-88fe-64276df78c1d.png)

**Comment by bep42** [comment]
Thanks for the feedback @nhan8g. I would love to hear you explain why. 
To my side, there's actually no needs.

**Comment by nhan8g** [comment]
I think it isn’t beautifull, there should be a button or an icon instead of just a word with underline

**Comment by matje123** [comment]
I think he is right.

**Comment by nhan8g** [comment]
Another IU Enhance I think should be, "Cancel" should replace with "NO" and it should be a button like "YES".
![image](https://user-images.githubusercontent.com/33117455/32098200-20a069dc-bb36-11e7-8a7f-403deaf3883e.png)

**Comment by nhan8g** [comment]
We do have UI designer, I think we should design beautifull icon/button for our Breeze instead of just a word

![image](https://user-images.githubusercontent.com/33117455/32098754-e93dd252-bb37-11e7-9d68-0051061975dd.png)

**Comment by viilveer** [comment]
The thing here in my opinion here is that they want you to distinct the primary and secondary action buttons.
Here, read this good article about button design and guidelines. https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150

Overally I think the current implementation is okay apart that in some places the button is orange, in some black.

**Comment by spectator-on-slack** [comment]
I think those Cancel, Back and Restore links do not require a button cause we want the user to pay more attention to the Create button. However, I do think the Copy link should be a button similar to Yes where it is transparent inside.

**Comment by dev0tion** [comment]
Implemented some of the feedback in #349.
The copy button will remain as is.
