### ISSUE TITLE
When I click on Privacy, unable to connect

### ISSUE THREAD

**Issue by spectator-on-slack** [stratisproject/Breeze#343]
When I click on Privacy from the Bitcoin wallet, it shows unable to connect message and I click OK but the message stays there.

![image](https://user-images.githubusercontent.com/29806775/32258450-c4f82c1a-be77-11e7-8475-7294f89495ae.png)

**Comment by dev0tion** [comment]
Hi @spectator-on-slack, could it be that you're not running Tor?
Please find info on how to run it here:
https://github.com/BreezeHub/Breeze/blob/tumblebit-alpha/Breeze.Documentation/alpha/tor.md#windows
