### ISSUE TITLE
2 step at Create/Restore Wallet

### ISSUE THREAD

**Issue by nhan8g** [stratisproject/Breeze#347]
I don' think it a good idea to split it to 2 step, just put all on 1 screen is enough and more comfortable.

![step1](https://user-images.githubusercontent.com/33117455/32358470-f0bca706-c078-11e7-8687-2f7af504223f.png)

![step2](https://user-images.githubusercontent.com/33117455/32358474-f553e87e-c078-11e7-8a06-041b4d76eeb2.png)

**Comment by Kick1986** [comment]
I also agree on that!

**Comment by dev0tion** [comment]
We've decided to keep our old approach on this one.
