### ISSUE TITLE
TBTC sending issue (timed out transactions are sent later)

### ISSUE THREAD

**Issue by viilveer** [stratisproject/Breeze#354]
I have produced following scenario:
1. Made new account
2. Sent some TBTC from https://testnet.manu.backend.hamburg/faucet
3. While having unconfirmed balance I started to send some funds to my own account
4. Sending timed out, i tried it few times.
5. After some time later, sending started to work (and balance was confirmed) but..

All my timed out transactions were also made... Check the timestamp of transactions.

![image](https://user-images.githubusercontent.com/1699307/32715249-2d9e8b10-c85a-11e7-963c-6666fe69d4d8.png)

**Comment by bokobza** [comment]
@viilveer Were all these transactions confirmed in the same block?
When a transaction is pending, the time is set to the time the transation was first seen on the network, but once it's confirmed, we change this time to be the one the block in which it's included.
So here, if all these transactions were included in the same block, the times should be the same.
For the time out, it's strange, maybe you weren't connected to enough nodes at the time?

**Comment by viilveer** [comment]
[node.txt](https://github.com/stratisproject/Breeze/files/1466584/node.txt)
Here are the logs aswell.

**Comment by bokobza** [comment]
I can see from the logs that you were connected to a few nodes, none of which was up to date with their blockchain. So effectively it behaved as if you were connected to none.
I think this is behaving as expected.

**Comment by viilveer** [comment]
If you ask me I would be surprised if it first says that it timed out and then later it completes the transaction. I might send the transaction again. I think that if this feature is supported (that timed out transactions are completed later on), those should be listed somewhere. my 2 cents only. :)

**Comment by dev0tion** [comment]
Fixed in a newer version of the Full Node
