### ISSUE TITLE
JavaScript error after successful Windows build

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/Breeze#355]
After building the win32-ia32 package I got the following error when tried to run the client:
![image](https://user-images.githubusercontent.com/910321/32878694-67f1b004-caa7-11e7-9bcc-b2dc4bbd850b.png)

Then I was stuck on the "loading the future" screen.

To reproduce it: 
1, Follow [the build instructions](https://github.com/stratisproject/Breeze/blob/master/Breeze.UI/README.md)
2, npm run package:windows
3, Run Breeze.exe

**Comment by dev0tion** [comment]
That's because you have to add the .NET daemon in the assets folder ;)
