### ISSUE TITLE
npm run start:web doesn't work (on Windows)

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/Breeze#356]
I tried to run the Breeze client in the browser on Windows with the npm run start:web command, as instructed in [the Breeze.UI readme](https://github.com/stratisproject/Breeze/blob/master/Breeze.UI/README.md).

npm returned the following:

> npm ERR! missing script: start:web

**Comment by dev0tion** [comment]
I need to update the documentation as we wont be supporting running Breeze in a browser anymore.
We are (and will be) using Electron for various functionality within the wallet, which is unavailable in a browser.
