### ISSUE TITLE
API: general-info need name, not walletName as required parameter

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/Breeze#358]
More examples would be nice in [the Breeze API documentation](https://github.com/stratisproject/Breeze/blob/master/Breeze.Documentation/ApiSpecification.md).

I followed the instruction, but the `general-info` API command needs the `name` query parameter, not `walletName` as mentioned in the documentation.

So the proper URL to test is something like this:
http://127.0.0.1:37220/api/wallet/general-info?name=TestWallet

(I could figure this out from [the wallet controller's source](https://github.com/stratisproject/StratisBitcoinFullNode/blob/24df960b94b669c2c7ea32d2fb57bcbb194ecde8/Stratis.Bitcoin.Features.Wallet/Controllers/WalletController.cs).)

**Comment by andrasfuchs** [comment]
Created a pull request for this: https://github.com/stratisproject/Breeze/pull/359

**Comment by dev0tion** [comment]
Thanks @andrasfuchs. Merged by @bokobza.

**Comment by bokobza** [comment]
thanks @andrasfuchs ! Closing with https://github.com/stratisproject/Breeze/pull/359
