### ISSUE TITLE
Package app for distribution for macOS, Windows and Linux

### ISSUE THREAD

**Issue by bokobza** [stratisproject/Breeze#361]
We need to package our apps so that downloading and installing them feels more natural to users.
We need:
* “auto update” support out of the box
* support for "uninstall" 
* (optional) additional portable app 

Usable technologies:
* inno setup (only for Windows - no portable app option)
* electron-builder (supports all 3 platforms)

@StratisIain @dev0tion

**Comment by dev0tion** [comment]
Fan of electron-builder, though I haven't checked out the signing part.

**Comment by bokobza** [comment]
Nice help article provided here: https://www.electron.build/code-signing
These things are usually quite finicky, but we might be surprised!

**Comment by matje123** [comment]
This would make the wallet look far more professional!

**Comment by D3m0nKingx** [comment]
Updating the status on this issue:

Windows and Linux builds have been successful with electron-builder. In addition to the Linux build we've been able to produce debian (.deb) file which can be provided through a ppa (personal package archive), therefore Linux users will be easily able to install breeze by running `sudo apt install breezewallet`

MAC build is being worked on, will update as progress is made.

see #373 #374 #375 #376 #377

**Comment by dev0tion** [comment]
Done
