### ISSUE TITLE
Breeze UI will not start when running on Node LTS 8.9

### ISSUE THREAD

**Issue by patrickafoley** [stratisproject/Breeze#363]
I am getting the following error when running `npm start` on node 8.9.1 on OSX 10.13.1:

13 verbose stack Error: Breeze@0.2.1 start: `npm-run-all --parallel webpack:watch electron:serve`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid Breeze@0.2.1
15 verbose cwd /Users/paf0/blockchain/Breeze/Breeze.UI
16 verbose Darwin 17.2.0
17 verbose argv “/usr/local/Cellar/node/8.9.1/bin/node” “/usr/local/bin/npm” “start”
18 verbose node v8.9.1
19 verbose npm  v5.5.1

**Comment by bokobza** [comment]
Hi @patrickafoley, have you still not managed to run this?
What's the full set of commands you're running?

**Comment by patrickafoley** [comment]
@bokobza sorry, yes, it does work. I'm not sure what fixed it, perhaps a reinstall of node.

**Comment by bokobza** [comment]
cool, thanks!
