### ISSUE TITLE
Simpler Releases

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#368]
I've just noticed you put out a bunch of releases, but I recently also noticed on the .net site that now it's enough to do only one for windows, one for linux and one for osx. https://stratisplatform.com/2017/11/21/breeze-wallet-mainnet-beta-release/

https://github.com/dotnet/docs/blob/master/docs/core/rid-catalog.md#windows-rids

**Comment by dev0tion** [comment]
You mean the portable version?
Interesting. Thanks.

**Comment by nopara73** [comment]
Yes.

**Comment by bokobza** [comment]
yeah indeed. I think we should try that when we have our next round of testing.

**Comment by nopara73** [comment]
So keep in mind. Closing.
