### ISSUE TITLE
Explore Electron.NET

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#380]
Hey guys, there's a new framework that makes Electron integration to .NET more seamless. It's promising. https://github.com/ElectronNET/Electron.NET  

Make sure to also watch this 20min youtube video: https://www.youtube.com/watch?v=nuM6AojRFHk

@NicolasDorier @dangershony @bokobza @dev0tion @wintercooled

**Comment by dev0tion** [comment]
VERY interesting! Cheers!

**Comment by NicolasDorier** [comment]
I saw that on /r/dotnet... seems a bit young though unsure about the stability.

**Comment by bokobza** [comment]
wow cool :-) Thanks for sharing.

**Comment by dev0tion** [comment]
@NicolasDorier yeah very young, but worth keeping an eye on

**Comment by bokobza** [comment]
No plan to move to anything else at the moment, and if anything, web.
Closing.
