### ISSUE TITLE
Platform specific build instructions

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/Breeze#383]
In the [README.md](https://github.com/stratisproject/Breeze/blob/master/README.md) of this repo there is a small description of how to build the BreezeD. It builds a platform independent .NET Core DLL image, but for the Breeze UI a platform specific executable is needed (as far as I know).

Could you include the complete instructions for the self-contained build as well? 

I finally figured out that I have to use the `dotnet publish --self-contained --runtime win-x64` command line in the BreezeD folder on my machine.

I think it would help others as well.

**Comment by dev0tion** [comment]
https://github.com/stratisproject/Breeze/tree/master/Breeze.UI
