### ISSUE TITLE
API port is 37220 by default (should be 37221 for Stratis)

### ISSUE THREAD

**Issue by andrasfuchs** [stratisproject/Breeze#384]
The default API port for the Stratis/Breeze daemons are 37220 for Bitcoin and 37221 for Stratis.

The current Breeze Wallet (v0.3.0 beta) looks for the APIs on port 37220. Shouldn't it be 37221?

**Comment by andrasfuchs** [comment]
Looking at the [api.service.ts](https://github.com/stratisproject/Breeze/blob/master/Breeze.UI/src/app/shared/services/api.service.ts) I can see that Breeze should look for both of them, and the port numbers defined there are correct.

Still, if I run the Breeze daemon with a command line arguments `stratis -testnet` the Breeze Wallet hangs at the "Loading the future" screen without showing any errors (except the "GET http://localhost:37220/api/wallet/files net::ERR_CONNECTION_REFUSED").

**Comment by dev0tion** [comment]
On wallet load it only checks the Bitcoin folder for wallets.
