### ISSUE TITLE
I can not recover my Stratis Core 

### ISSUE THREAD

**Issue by Maxim3474** [stratisproject/Breeze#404]
Hi dear Support, i used my Staking Wallet (Stratis QT 2.0.0.2) August 2018.
Now i have tried to recover my wallet, but i didnt know secret words, i have only Stratis.dat and password, it was enough for recovering for old version (Staking Wallet QT 2.0.0.2.) August 2018, i coudnt get that secret words form old version Staking Wallet.
What can you suggest i do? i tried Stratis QT but it isnt synchronizing. 
I downloaded  Stratis QT 2.0.0.2 and opened my Wallet.dat through my password but i didnt see threre Passphrase, thats problem and it isnt synchronyzing
Thanks a lot

**Comment by dev0tion** [comment]
Hi @Maxim3474, 

Qt and Stratis Core are not using the same wallet format, so you can't recover a Qt wallet on Core.
Please install Qt v2.0.0.5: https://github.com/stratisproject/stratisX/releases/tag/v2.0.0.5
Let it sync with your wallet file and then use the migration guide to switch over to Core: https://stratisplatform.com/wp-content/uploads/2018/12/Migrating-to-Stratis-Core.pdf

Let me know if that helps you.

**Comment by Maxim3474** [comment]
Hi, it helped really, i downloaded Stratis Qt v2.0.0.5, it has already synchronyzed and fortunatelly i could open my wallet.dat =)))))
Now i am waiting, when Stratis Core has synchronized, then i will transfer coins.
Is Synchronizing ok (i mean Stratis Core), it has been synchronizing more than 24 hours, and synchronizing Process doesnt display like on Stratis Qt.
Thanks a lot!
![Stratis Core](https://user-images.githubusercontent.com/40694667/55816159-5243a700-5afa-11e9-942d-9b7031497db6.png)

**Comment by Maxim3474** [comment]
Hi =) i have a little question, Stratis Core is synchronizing now and it has processed 435614 
 out of 435614 blocks. There is no pregress more, it has changed nothing for 12 hours
Maybe it has stoppped synchronizing or it is ok so? 
Thanks a lot

**Comment by Maxim3474** [comment]
Hi, i am again very sad =( i have sent all my coins to Stratis Core.
Is all coins lost? =((
![Stratis Core](https://user-images.githubusercontent.com/40694667/55838211-5092d700-5b2c-11e9-8b9c-b37c710c563c.png)

**Comment by Maxim3474** [comment]
Hi dear Pieterjan, i have already done all things, all coins are on new Wallet (Breeze Wallte) =)) i store there my btc too.
i have one Question, do i have to save:
1) Wallet.json (bitcoin/main)
2) Wallet.json (stratis/stratsimain)
i am very interested in one thing, could i open my wlllet only owning my password and 2wallet.json files without a passphrase and secret words like in old vesion Stratis Qt 2.0.0.5? In Stratis Qt 2.0.0.5. i need only wallet.dat and my password. 
How logn will Stratis Qt work, are you going to close Stratis Qt down.
If i have password, passphrase, secret words can i store my coins 5 years without controlling my wallet every month, i think  i can recover it anytime now.
Really thanks for your support, you have really helped me a lot =)))))

**Comment by dev0tion** [comment]
You don't have to save them for Breeze. You have to save your secret words and passphrase, those can recover the wallet files.
Qt will at some point become deprecated and switching to Core/Breeze will be advised at that point.
This new wallet implementation (HD wallet) will be supported for a long time, there's no saying for how long though. If there's some new breakthrough technology, we might switch, but then it will be clearly stated way before that switch happens.

You're welcome, I'm closing this issue.
