### ISSUE TITLE
Backup wallet without Google Drive

### ISSUE THREAD

**Issue by RobertHosking** [stratisproject/Breeze#407]
Is there a way to backup/import breeze wallet without relying on Google Drive? Maybe using a developer command?

**Comment by dev0tion** [comment]
Why would you need to rely on Google Drive? 
Have you been contacted by a possible scammer?

A Breeze wallet can be restored using your 12 words and passphrase. That's all.

**Comment by RobertHosking** [comment]
No scammers. 
I get this notice in the top right of the app informing me to backup my wallet. However, I don't have Google so this "Backup Now" button doesn't do anything. Can I reveal my seed phrase some other way?

**Comment by dev0tion** [comment]
Are you certain you're using Breeze? Can you post a screenshot? Make sure you don't reveal any private info.

**Comment by RobertHosking** [comment]
I mistook this for github.com/breez/breezmobile
