### ISSUE TITLE
I can not synchronize my Strat from Coinomi wallet to Stratis Core

### ISSUE THREAD

**Issue by glankminh** [stratisproject/Breeze#408]
Hi dear bros,

I have currently owned some STRAT coins in my Coinomi wallet which have not been swapped yet to STRAX for using (trading/holding).

I am using now Stratis Core 2.2.1 to synchronize those coins but there has been nothing happening when I am doing it (no balance updated).

Could you guys here please help how can I use those STRAT (in Coinomi Wallet)?

Thanks so much.

**Comment by dev0tion** [comment]
Hi, please join our Discord server and head over to the #support channel, they will gladly assist you with this issue.
https://discordapp.com/invite/9tDyfZs
