### ISSUE TITLE
What ports are you using?

### ISSUE THREAD

**Issue by nopara73** [stratisproject/Breeze#79]
I am documenting the local ports used by related softwares [here](https://github.com/nopara73/HiddenWallet/blob/master/HiddenWallet/HiddenWallet.Docs/Ports.md). Did you decided on what should will be the final port for Breeze API and maybe Stratis FN RPC?    
  
|Port | Application |
|---- | ---- |
|37120  | HiddenWallet API |
|37121  | Tor socks port used by HiddenWallet |
|37122  | Tor control port used by HiddenWallet |
|37123  | NTumbleBit server |
|9050  | Default Tor socks port |
|9051  | Default Tor control port |
|9150  | Tor socks port used by Tor Browser |
|9151  | Tor control port used by Tor Browser |
|8333  | Bitcoin Core RPC |
|  | Stratis: Breeze Wallet API |

**Comment by dangershony** [comment]
The Breeze api will have more then one port as it depends on what network is used (Stratis/Bitcoin)
But those ports are intended for internal use only as a way for the GUI to talk with the api.

**Comment by dangershony** [comment]
Probably the only external port really important in you list is the (37123 NTumbleBit server) as the TB client will need to connect to that right?

**Comment by nopara73** [comment]
The client doesn't. It connects, to the ip address of the server over the internet. The tumbler default port is only for local testing. It's not a very important list, but it turned out to be handy for me for quick lookup, so I thought I document it more extensively. Let's get back to Breeze's ports when you have it later (if won't forget it)

**Comment by bokobza** [comment]
@nopara73 I'm reopening this so we don't forget :-)

**Comment by bokobza** [comment]
@nopara73 
by default the bitcoin node uses port 5000 and the Stratis node uses port 5105.

**Comment by nopara73** [comment]
@bokobza Both of those ports [are](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5105) [reserved](https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5000). I described [here](https://github.com/nopara73/HiddenWallet/blob/master/HiddenWallet/HiddenWallet.Docs/Ports.md), how I have chosen my ports.

**Comment by bokobza** [comment]
Indeed, although I don't think it should be a problem. 
In our case, ports 5000 and 5105 are for private use, not for use on public networks.
Also, these ports are configurable by the UI, in case they conflict with another application running on the same system.

**Comment by nopara73** [comment]
@bokobza I added to [my list](https://github.com/nopara73/HiddenWallet/blob/master/HiddenWallet/HiddenWallet.Docs/Ports.md). Am I suspecting right that it's this the same for Breeze, too?

**Comment by bokobza** [comment]
yeah same for Breeze mate, thank you. good work @nopara73

**Comment by nopara73** [comment]
Reopened, because using the default 5000 port is leads to conflicts.

**Comment by nopara73** [comment]
Replaced by: https://github.com/stratisproject/Breeze/issues/240
