### ISSUE TITLE
Investigate whether it makes more sense to break Breeze into multiple daemons

### ISSUE THREAD

**Issue by bokobza** [stratisproject/Breeze#87]
At the moment we have 1 daemon that can spin any configuration we want:
Stratis/Spv wallet/testnet
Bitcoin/Full node/Main
etc

Maybe having multiple daemons makes more sense?
Let's revisit this.

**Comment by dangershony** [comment]
My preference is:
A daemon per coin (each coin can specify test/main)
And a daemon per Fullnode/Lightwallet
(maybe even a new daemon for a tumbling Breeze wallet

Breeze would then become a collection of daemons.

**Comment by dev0tion** [comment]
I think we've pretty much cover this. Closing.
