### ISSUE TITLE
Oracle VM Virtualbox

### ISSUE THREAD

**Issue by MisterCharlie** [stratisproject/Breeze#89]
Hi,

Question, after downloading the .ova file to install breeze on the Virtualbox i had the problem that it only can import appliances with the extention .ovf ,can you tell me how this can be solved?

**Comment by MisterCharlie** [comment]
Oke i found it already, just had to open .ova file and it went into the import appliances of the Virtualbox:)

**Comment by dev0tion** [comment]
Good :)
