### ISSUE TITLE
I can't create a wallet

### ISSUE THREAD

**Issue by Signy26** [stratisproject/Breeze#96]
I tried your pre-alpha breeze wallet version and I can't create a wallet, I click 'Create Wallet' button and nothing happens, I tried to reload view but it brings me back to home screen where I can choose between to create or restore wallet

**Comment by bokobza** [comment]
@Signy26 is this still an issue?

**Comment by Signy26** [comment]
Now everything seems okay with a v0.1.0 alpha, good luck guys, I hope this project going to be big and succesful.

Best regards, Gytis. 


 

/*<![CDATA[*/
 p.c1 {color: #666; font-size: small}
/*]]>*/


 
----- Reply to message -----
Subject: Re: [stratisproject/Breeze] I can't create a wallet (#96)
Date: 2017 m. birželio 27 d., antradienis 16:22:44
